// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionRecordApp.Entities;

#nullable disable

namespace TransactionRecordApp.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20240131024946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionRecordApp.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("SharePrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            CompanyName = "Apple Inc.",
                            Quantity = 2,
                            SharePrice = 194.62,
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            TransactionId = 2,
                            CompanyName = "Ford Motors Company",
                            Quantity = 5,
                            SharePrice = 8.5,
                            TickerSymbol = "F"
                        },
                        new
                        {
                            TransactionId = 3,
                            CompanyName = "Alphabet Inc.",
                            Quantity = 1,
                            SharePrice = 1022.37,
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            TransactionId = 4,
                            CompanyName = "Microsoft Corporation",
                            Quantity = 10,
                            SharePrice = 107.70999999999999,
                            TickerSymbol = "MSFT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
